/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author raf
 */
public class Jogar extends javax.swing.JFrame {

    /**
     * Creates new form Jogar
     */
    public Jogar() {
        initComponents();
        jB_1.setText("");
        jB_2.setText("");
        jB_3.setText("");
        jB_4.setText("");
        jB_5.setText("");
        jB_6.setText("");
        jB_7.setText("");
        jB_8.setText("");
        jB_9.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Background = new javax.swing.JPanel();
        jP_BGTop = new javax.swing.JPanel();
        jP_BGTittle = new javax.swing.JPanel();
        jL_TikTakToe = new javax.swing.JLabel();
        jL_Credito = new javax.swing.JLabel();
        jL_JogoDaVelha = new javax.swing.JLabel();
        jP_BGBottom = new javax.swing.JPanel();
        jP_BGJogo = new javax.swing.JPanel();
        jP_B2 = new javax.swing.JPanel();
        jB_2 = new javax.swing.JButton();
        jP_B3 = new javax.swing.JPanel();
        jB_3 = new javax.swing.JButton();
        jP_B1 = new javax.swing.JPanel();
        jB_1 = new javax.swing.JButton();
        jP_B4 = new javax.swing.JPanel();
        jB_4 = new javax.swing.JButton();
        jP_B7 = new javax.swing.JPanel();
        jB_7 = new javax.swing.JButton();
        jP_B5 = new javax.swing.JPanel();
        jB_5 = new javax.swing.JButton();
        jP_B8 = new javax.swing.JPanel();
        jB_8 = new javax.swing.JButton();
        jP_B9 = new javax.swing.JPanel();
        jB_9 = new javax.swing.JButton();
        jP_B6 = new javax.swing.JPanel();
        jB_6 = new javax.swing.JButton();
        jB_Menu = new javax.swing.JButton();
        jL_MensagemJogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_Background.setBackground(new java.awt.Color(153, 153, 153));

        jP_BGTop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jP_BGTopLayout = new javax.swing.GroupLayout(jP_BGTop);
        jP_BGTop.setLayout(jP_BGTopLayout);
        jP_BGTopLayout.setHorizontalGroup(
            jP_BGTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jP_BGTopLayout.setVerticalGroup(
            jP_BGTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jP_BGTittle.setBackground(new java.awt.Color(255, 255, 255));

        jL_TikTakToe.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jL_TikTakToe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_TikTakToe.setText("Tik Tak Toe");

        jL_Credito.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jL_Credito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_Credito.setText("Por Rafael Ferreira Goulart");

        jL_JogoDaVelha.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jL_JogoDaVelha.setText("#");

        javax.swing.GroupLayout jP_BGTittleLayout = new javax.swing.GroupLayout(jP_BGTittle);
        jP_BGTittle.setLayout(jP_BGTittleLayout);
        jP_BGTittleLayout.setHorizontalGroup(
            jP_BGTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BGTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BGTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_BGTittleLayout.createSequentialGroup()
                        .addComponent(jL_TikTakToe, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_JogoDaVelha, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jP_BGTittleLayout.createSequentialGroup()
                        .addComponent(jL_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jP_BGTittleLayout.setVerticalGroup(
            jP_BGTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BGTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BGTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_TikTakToe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_JogoDaVelha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jP_BGBottom.setBackground(new java.awt.Color(255, 255, 255));

        jP_BGJogo.setBackground(new java.awt.Color(153, 153, 153));

        jB_2.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_2.setText("O");
        jB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B2Layout = new javax.swing.GroupLayout(jP_B2);
        jP_B2.setLayout(jP_B2Layout);
        jP_B2Layout.setHorizontalGroup(
            jP_B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B2Layout.setVerticalGroup(
            jP_B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_3.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_3.setText("X");
        jB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B3Layout = new javax.swing.GroupLayout(jP_B3);
        jP_B3.setLayout(jP_B3Layout);
        jP_B3Layout.setHorizontalGroup(
            jP_B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B3Layout.setVerticalGroup(
            jP_B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_1.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_1.setText("X");
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B1Layout = new javax.swing.GroupLayout(jP_B1);
        jP_B1.setLayout(jP_B1Layout);
        jP_B1Layout.setHorizontalGroup(
            jP_B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B1Layout.setVerticalGroup(
            jP_B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_4.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_4.setText("O");
        jB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B4Layout = new javax.swing.GroupLayout(jP_B4);
        jP_B4.setLayout(jP_B4Layout);
        jP_B4Layout.setHorizontalGroup(
            jP_B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B4Layout.setVerticalGroup(
            jP_B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_7.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_7.setText("X");
        jB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B7Layout = new javax.swing.GroupLayout(jP_B7);
        jP_B7.setLayout(jP_B7Layout);
        jP_B7Layout.setHorizontalGroup(
            jP_B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B7Layout.setVerticalGroup(
            jP_B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_5.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_5.setText("X");
        jB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B5Layout = new javax.swing.GroupLayout(jP_B5);
        jP_B5.setLayout(jP_B5Layout);
        jP_B5Layout.setHorizontalGroup(
            jP_B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B5Layout.setVerticalGroup(
            jP_B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_8.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_8.setText("O");
        jB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B8Layout = new javax.swing.GroupLayout(jP_B8);
        jP_B8.setLayout(jP_B8Layout);
        jP_B8Layout.setHorizontalGroup(
            jP_B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B8Layout.setVerticalGroup(
            jP_B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_9.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_9.setText("X");
        jB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B9Layout = new javax.swing.GroupLayout(jP_B9);
        jP_B9.setLayout(jP_B9Layout);
        jP_B9Layout.setHorizontalGroup(
            jP_B9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B9Layout.setVerticalGroup(
            jP_B9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jB_6.setFont(new java.awt.Font("Poor Richard", 1, 40)); // NOI18N
        jB_6.setText("O");
        jB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_B6Layout = new javax.swing.GroupLayout(jP_B6);
        jP_B6.setLayout(jP_B6Layout);
        jP_B6Layout.setHorizontalGroup(
            jP_B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_6, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_B6Layout.setVerticalGroup(
            jP_B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_B6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_6, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_BGJogoLayout = new javax.swing.GroupLayout(jP_BGJogo);
        jP_BGJogo.setLayout(jP_BGJogoLayout);
        jP_BGJogoLayout.setHorizontalGroup(
            jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BGJogoLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jP_B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_BGJogoLayout.createSequentialGroup()
                        .addComponent(jP_B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP_B9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_BGJogoLayout.createSequentialGroup()
                        .addGroup(jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jP_B2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_B5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jP_B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jP_B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_BGJogoLayout.setVerticalGroup(
            jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BGJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_BGJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_B9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jB_Menu.setBackground(new java.awt.Color(153, 153, 153));
        jB_Menu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jB_Menu.setText("Menu");
        jB_Menu.setToolTipText("Retorna ao menu. Você perderá o jogo atual");
        jB_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_MenuActionPerformed(evt);
            }
        });

        jL_MensagemJogo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jL_MensagemJogo.setText("mensagem");

        javax.swing.GroupLayout jP_BGBottomLayout = new javax.swing.GroupLayout(jP_BGBottom);
        jP_BGBottom.setLayout(jP_BGBottomLayout);
        jP_BGBottomLayout.setHorizontalGroup(
            jP_BGBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_BGBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BGBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_BGBottomLayout.createSequentialGroup()
                        .addComponent(jL_MensagemJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Menu))
                    .addComponent(jP_BGJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_BGBottomLayout.setVerticalGroup(
            jP_BGBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BGBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_BGJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_BGBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_MensagemJogo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_BackgroundLayout = new javax.swing.GroupLayout(jP_Background);
        jP_Background.setLayout(jP_BackgroundLayout);
        jP_BackgroundLayout.setHorizontalGroup(
            jP_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jP_BGTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_BGTop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_BGBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_BackgroundLayout.setVerticalGroup(
            jP_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BackgroundLayout.createSequentialGroup()
                .addComponent(jP_BGTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_BGTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_BGBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_MenuActionPerformed
        JogoGui menu = new JogoGui();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jB_MenuActionPerformed

    private void joga(int botao) {
        
    }
    
    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
        joga(0);
    }//GEN-LAST:event_jB_1ActionPerformed

    private void jB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2ActionPerformed
        joga(1);
    }//GEN-LAST:event_jB_2ActionPerformed

    private void jB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ActionPerformed
        joga(2);
    }//GEN-LAST:event_jB_3ActionPerformed

    private void jB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_4ActionPerformed
        joga(3);
    }//GEN-LAST:event_jB_4ActionPerformed

    private void jB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_5ActionPerformed
        joga(4);
    }//GEN-LAST:event_jB_5ActionPerformed

    private void jB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_6ActionPerformed
        joga(5);
    }//GEN-LAST:event_jB_6ActionPerformed

    private void jB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_7ActionPerformed
        joga(6);
    }//GEN-LAST:event_jB_7ActionPerformed

    private void jB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_8ActionPerformed
        joga(7);
    }//GEN-LAST:event_jB_8ActionPerformed

    private void jB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_9ActionPerformed
        joga(8);
    }//GEN-LAST:event_jB_9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_1;
    private javax.swing.JButton jB_2;
    private javax.swing.JButton jB_3;
    private javax.swing.JButton jB_4;
    private javax.swing.JButton jB_5;
    private javax.swing.JButton jB_6;
    private javax.swing.JButton jB_7;
    private javax.swing.JButton jB_8;
    private javax.swing.JButton jB_9;
    private javax.swing.JButton jB_Menu;
    private javax.swing.JLabel jL_Credito;
    private javax.swing.JLabel jL_JogoDaVelha;
    private javax.swing.JLabel jL_MensagemJogo;
    private javax.swing.JLabel jL_TikTakToe;
    private javax.swing.JPanel jP_B1;
    private javax.swing.JPanel jP_B2;
    private javax.swing.JPanel jP_B3;
    private javax.swing.JPanel jP_B4;
    private javax.swing.JPanel jP_B5;
    private javax.swing.JPanel jP_B6;
    private javax.swing.JPanel jP_B7;
    private javax.swing.JPanel jP_B8;
    private javax.swing.JPanel jP_B9;
    private javax.swing.JPanel jP_BGBottom;
    private javax.swing.JPanel jP_BGJogo;
    private javax.swing.JPanel jP_BGTittle;
    private javax.swing.JPanel jP_BGTop;
    private javax.swing.JPanel jP_Background;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    // End of variables declaration//GEN-END:variables
}
